<?php

namespace TLB\WPBundle\Entity\Repository;

use Doctrine\Common\Collections\ArrayCollection;

use Doctrine\ORM\EntityRepository;
use TLB\WPBundle\Entity\TLBComment;
/**
 * TLBCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TLBCommentRepository extends EntityRepository
{
	protected $wpService;
	
	public function setWpService($wpService)
	{
		$this->wpService = $wpService;
	}
	
	public function getComentariosPost($postId)
	{
		$comentarios = $this->wpService->obtenerComentarios($postId);
		$coleccionComentarios = new ArrayCollection();
		foreach($comentarios as $comentario)
		{
			$objetoComentario = new TLBComment();
			$objetoComentario->setCommentId($comentario->comment_ID);
			$objetoComentario->setCommentPostId($comentario->comment_post_ID);
			$objetoComentario->setCommentAuthor($comentario->comment_author);
			$objetoComentario->setCommentAuthorEmail($comentario->comment_author_email);
			$objetoComentario->setCommentAuthorUrl($comentario->comment_author_url);
			$objetoComentario->setCommentDate($comentario->comment_date);
			$objetoComentario->setCommentContent($comentario->comment_content);
			$coleccionComentarios->add($objetoComentario);
		}
		return $coleccionComentarios;
	}
	
}
